#!/bin/bash
if [ $# = 1 ]
then
    if [ "$(id -u)" != "0" ]
    then
            echo "Sorry, you are not root."
    elif [ $1 = 'all' -a "$(id -u)" = "0" ]
    then
        coverage run -m --source=qwifi unittest discover
	coverage report -m
    elif [ $1 = 'log' ]
    then
        ./test_log.py
    elif [ $1 = 'db' ]
    then
        ./test_data_base.py
    elif [ $1 = 'util' ]
    then
        ./test_util.py
    fi
else
    if [ "$(id -u)" != "0" ]; then
	    echo "Sorry, you are not root."
    fi
    echo "sudo ./test all   -----> run all unit tests"
    echo "sudo ./test log   -----> run log unit tests"
    echo "sudo ./test db    -----> run db unit tests"
    echo "sudo ./test util  -----> run util unit tests"
fi
